### ISSUE TITLE
Image loading

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#12]
Wonder if there is a default way to load images with:
* srcset
* lazy loading
* lqip

Possible we get there just with a standard img tag, but it seems like we might want an image component that does some of this for us.

The data one looks the most promising to me, but i haven't looked to see if it would support what we get from wordpress (or what we could extract from #8).

https://www.datocms.com/blog/offer-responsive-progressive-lqip-images-in-2020
https://github.com/datocms/react-datocms/blob/master/src/Image/index.tsx
https://www.gatsbyjs.org/packages/gatsby-image/
https://github.com/cloudinary/cloudinary-react

**Comment by kylehotchkiss** [comment]
Let's go with Next.js' official `<Image>` component. It was developed alongside the Chrome team and supports sourcesets, lazy loading. It will also do backend magic to support serving optimized sizes, and the most optimized format without requiring any configuration.

I've begun to use `<Image>` on my own photosite and found it to be easy to adopt. My only real gripe is when you use Next.js/Vercel to generate the images, the resized images don't seem to stay cached on the edges very long. `<Image>`'s built in support for cloudinary (which is free for many sites) would be a good best practice for us to support.

I was going to leave a note about about rigid the width/height requirements are and how images will get warped if those values aren't set right, _but_ I just saw a new `<Image>` prop in the docs `layout`: https://nextjs.org/docs/api-reference/next/image#layout - if you set this value to `fill`, the image will fill the set bounds but won't get warped. <Image> doesn't yet otherwise support a cropping option.

Regarding LQIP,  we could build a component to wrap around `<Image>` to show a LQIP before the image loads, but in my experience LQIP generation with Next is not straightforward. You have to implement the LQIP into the getStaticProps function and filter through everything from GraphQL to figure out where the image urls are for LQIP are and then inject those back into the graphql response for further processing into the actual page later on. 

After thinking through this, I don't at the moment see what we need to add on top of `<Image>` to take advantage of it. Maybe we should focus on processing WYSWIG html to get out normal images and convert them to `<Image>`?

**Comment by ccorda** [comment]
Totally agree on `next/image`

What I see as relevant here:

* We need to have support for pulling image dimensions out of WP graphql.
* An example of using that with next/image to load images into the site, for example with the images on the flex + hero module.
* Optionally converting the default Next resizing to use Cloudinary.
* Using the flex module ordering to say that that above the fold (maybe first 2 flex modules?) should have `priority`

**Comment by ccorda** [comment]
Thanks @kylehotchkiss. Going to close this out as we have a baseline. Will file some followups as I encounter things on our next few projects.
