### ISSUE TITLE
GraphCDN and Vercel Cache Invalidation

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#226]
On update, ideally we would:
1) Purge graphdn
2) Revalidate in Next

Next now has support for on demand revalidation:
https://vercel.com/docs/concepts/next.js/incremental-static-regeneration#on-demand-revalidation

And there is a GraphCDN plugin now:
https://docs.stellate.co/docs/graphcdn-wordpress-plugin

It requires wpgraphql 1.7, which is a current blocker for us #216

**Comment by ccorda** [comment]
Moving to ready status, @kylehotchkiss to test out stellate plugin

**Comment by kylehotchkiss** [comment]
Since the plugin code isn't very long, I gave it a review to understand how it's working. It seems pretty well designed for a vanilla Wordpress install, but I did notice that post types and taxonomies were hardcoded, so I'd like to see in practice whether custom post types and taxonomies properly work with this plugin. The best way to accomplish this would be setting up the plugin and watching the Stellate dashboard to see what the incoming requests look like.

> Can we customize so that things like editing a menu, or changing a global ACF option purge all

There isn't specifically a cache clear that occurs when editing a menu, but there is function in the plugin I wonder if we can call externally `stellate_purge_all()` that is connected with the plugin's auth variables.

**Comment by kylehotchkiss** [comment]
Good news: the Stellate plugin does support custom post types and taxonomies
Bad news: there's a bug in the plugin that effectively means we can't clear custom post types or taxonomies until resolved. If we're having a hard time getting it resolved, we can make an adjustment to the CPT definition of every site we wish to roll this out on by capitalizing the graphql single/plural name but I anticipate this could cause other side effects.

I sent the following bug report to them over their Intercom chat because I couldn't find a contact email address:

```
Hello,

I found a bug in your Stellate Wordpress plugin but couldn't find a repo to file this bug for (along with a PR since the fix is straightforward).

My company relies pretty heavily on custom post types and taxonomies within Wordpress and I'm glad to see the Stellate plugin supports them, but the way the purge call is generated doesn't perform the auto-capitalization that WP-GraphQL does. For example, we setup CPTs like this:

`
register_post_type('partnerships', array( 
    ... 
    'graphql_single_name'   => 'partnership',
    'graphql_plural_name'   => 'partnerships',
));
`

WP-GraphQL auto-capitalizes those to Partnership/Partnerships for us, they aren't invalid values.

But when I setup the Stellate WP Plugin, the generated purge query looks like this:

`
mutation WPStellateIntegration($soft: Boolean $partnershipIds: [ID!]) {
    purgeartnershipById: purgepartnership(soft: $soft, id: $partnershipIds)
}
`

Which causes the following error:

`
{
  "errors": [
    {
      "message": "Cannot query field \"purgepartnership\" on type \"Mutation\". Did you mean \"purgePartnership\", \"purgeQuery_partnership\", or \"purgeQuery_partnerships\"?",
      "locations": [ 
        {
          "line": 2,
          "column": 5
        }
      ]
    }
  ]
}
`

The error is easily resolved by capitalizing the Partnership in `purgepartnership`.

In the code, the auto-capitalization could be applied here:

`
$GLOBALS['gcdn_purges'][$post_type_object->graphql_single_name] = [];
`

and here to resolve on custom taxonomies:

`
$GLOBALS['gcdn_purges'][$args['graphql_single_name']] = [];
`

Can you please make sure this gets sent to the correct person, and consider open-sourcing the Wordpress plugin so that the community can contribute bugfixes on issues like these?
```

**Comment by ccorda** [comment]
One note here, just realized the plugin is incompatible with multisite. Don't think that's a blocker in bubs-next as it's currently only single site, but we will want to work with Stellate to get multisite compatible before working on #236 .
