### ISSUE TITLE
Docker Restart Policy

### ISSUE THREAD

**Issue by kylehotchkiss** [patronage/bubs-next#243]
When I re-open docker desktop after it's been closed for a system restart or to increase battery life, it always tries to open a random combination of instances. Even the wordpress and sql instances seem randomly selected and are not limited to just one project.

When this happens and you try to start a project in your terminal with `docker compose up`, you get an error like:

```
Attaching to client-db-1, fwdus-wordpress-1
Error response from daemon: driver failed programming external connectivity on endpoint client-db-1 (***): Bind for 0.0.0.0:3307 failed: port is already allocated
```

which persists until the other instances are stopped.

[We traced this back to our `restart: always` config in docker-compose.yml](https://github.com/patronage/bubs-next/blob/main/wordpress/docker-compose.yml#L10). 

[Let's consider a different `restart:` policy](https://www.baeldung.com/ops/docker-compose-restart-policies) to disable this behavior

**Comment by ccorda** [comment]
To use restart policies, Docker provides the following options:

no: Containers won't restart automatically.
on-failure[:max-retries]: Restart the container if it exits with a non-zero exit code, and provide a maximum number of attempts for the Docker daemon to restart the container.
always: Always restart the container if it stops.
unless-stopped: Always restart the container unless it was stopped arbitrarily, or by the Docker daemon.

**Comment by ccorda** [comment]
To test this, i'd start a docker container, then exit docker, and restart. With our current setup, I'd consistently get an outcome outcome where multiple conainers are running 1/2 (one wordpress, one db). This is not ideal and I'd rather a case where nothing open.

Ideally if somehow there is an error in a running container, it's able to self-restart.

Nice to have, trying to load up a new one forces the old ones to close.

* `on-failure`. When you restart docker, the last docker container running successfully re-starts. Trying to load a different one doesn't break the current.
* `"no"` When you restart docker, you have a clean slate, nothing running. Trying to load a different one doesn't break the current.

I don't have a strong opinion, but I'm leaning towards `"no"`, as it gives you a clean docker on startup, and otherwise I don't believe our containers really fail and need to be restarted (and they're not meant for production where you might want that)
