### ISSUE TITLE
Restore conventional commits action

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#250]
We used to have conventional commits enforced, can we get that back for this, bubs-timber, and also our private fired-up-launch repo?

**Comment by kylehotchkiss** [comment]
I found out what happened to the old one! https://github.com/zeke/semantic-pull-requests It died with Heroku's free tier. Zeke recommended https://github.com/Ezard/semantic-prs which can be installed via marketplace here: https://github.com/marketplace/semantic-prs. I like this technique since we're not hardcoding actions that would apply to cloned copies of pubs-next.

**Comment by kylehotchkiss** [comment]
![Screenshot 2023-02-09 at 3 59 25 PM](https://user-images.githubusercontent.com/108172/217966168-703d60ec-bc96-46ef-97be-da0c4b1d7c58.png)

Looks like it's already working! Moving this to "In Review"

**Comment by ccorda** [comment]
Working great -- thanks @kylehotchkiss.
