### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#40]
The current `README.md` is growing, and we've always wanted it to be fairly minimal, since its primary purpose is to be the readme on a new site after cloned from the project template.

I was thinking that adding a docs folder might be nice, because then:

1) Our documentation on how to develop with bubs is version controlled.
2) We could show how you can incorporate markdown into what is otherwise a wordpress powered dynamic site.

@kylehotchkiss thoughts on approach here?

**Comment by kylehotchkiss** [comment]
Is our goal to actually publish these pages on our bubs site? Should the bubs docs be published on any site cloned from bubs-next?

I like the idea of using MDX for these. If we want things to live at the top level `/docs` in repo, we'll need to make an api to expose those to getStaticPaths. Otherwise, a folder full of MDX docs could work, but it'll be pretty nested in the repo `/website/src/pages/docs`.

**Comment by ccorda** [comment]
My main goal is just to be able to have a place to put things that isn't the growing README. I suppose an interim solution is just to create a `docs` folder for now, then we can always figure out where to publish later.

**Comment by ccorda** [comment]
Resolved by #50
