### ISSUE TITLE
Use Next SEO

### ISSUE THREAD

**Issue by ccorda** [patronage/bubs-next#46]
Currently we have a custom `Meta` component that let's a page pass up common variables like title, description, and a Yoast SEO object via graphql.

It relies on next/head, and works pretty well. But there is the [next-seo](https://github.com/garmeeh/next-seo) plugin that does much more. Should we migrate to using it?

Some things I like about it:

* Define more defaults either in its own config file, or in constants.
* `dangerouslySetAllPagesToNoIndex` which could be used on preview branches to ensure they don't get indexed.
* Ability to respect page level yoast configs like no-index, canonical, etc.
* Support for alternate open graph plugins like Video, Article, etc.
* JSON-LD structural data for various types of content

**Comment by kylehotchkiss** [comment]
I like how it's a fix-it-and-forget-it type of setup that could add the next big social network's OG tags with a package upgrade. Since we've been using Yoast so long, there might be meta tags we might not be aware of being set (have we ever intensionally written a canonical URL meta tag on our own, for example?) and a package like next-seo lets us rely on somebody else's expertise to make sure our share metadata is solid.

I like the JSON-LD support:
![https://developers.google.com/search/docs/data-types/images/non-amp-article.png](https://developers.google.com/search/docs/data-types/images/non-amp-article.png)

Maybe this could make our share image generator tools easier too?
